version: '3.8'

services:
  mongo-db:
    container_name: mongodb
    image: mongo:6.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-user
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017

  postgres:
    container_name: postgis
    image: postgis/postgis:16-3.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: smizc2024
      POSTGRES_USER: smizc
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432